services:
  redis:
    container_name: redis-cache
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    command: ['redis-server']
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - mern

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    ports:
      - '8081:8081'
    networks:
      - mern

volumes:
  redis:
    name: redis
    driver: local
