version: "3.9"
services:
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

networks:
  redis:
    name: redis

volumes:
  redis_data:
    name: redis_data
    driver: local
